all: true
include:
  - app.ts
  - lib/**/*.ts
extends: "@istanbuljs/nyc-config-typescript"
exclude:
  - lib/handlers/asm-docs.ts
  - lib/compilers/fake-for-test.ts
report-dir: ./out/coverage
reporter:
  - lcov
require:
  - esm
  - source-map-support/register
  - ts-node/register
